const categories = {
  "Document Structure": { tags: ["<!doctype", "<html", "<head", "<body", "<title", "<meta", "<link", "<script"], name: "Document Structure" },
  "Layout & Containers": { tags: ["<div", "<span"], name: "Layout & Containers" },
  "Headings & Text": { tags: ["<h1", "<h2", "<h3", "<h4", "<h5", "<h6", "<p", "<br", "<hr"], name: "Headings & Text" },
  "Links & Media": { tags: ["<a", "href=", "<img", "src="], name: "Links & Media" },
  "Lists": { tags: ["<ul", "<ol", "<li"], name: "Lists" },
  "Forms": { tags: ["<form", "<label", "<input", "<textarea", "<select", "<option", "<button"], name: "Forms" },
  "Semantic Layout": { tags: ["<header", "<main", "<section", "<article", "<aside", "<footer", "<nav"], name: "Semantic Layout" },
  "Text Semantics": { tags: ["<strong", "<em", "<small", "<mark", "<code", "<pre", "<blockquote", "<q", "<cite", "<time"], name: "Text Semantics" },
  "Media": { tags: ["<picture", "<source", "<video", "<audio", "<figure", "<figcaption", "<iframe"], name: "Media" },
  "Interactive Elements": { tags: ["<details", "<summary"], name: "Interactive Elements" },
  "Advanced Forms": { tags: ["<fieldset", "<legend", "<datalist", "<optgroup", "<output", "<progress", "<meter"], name: "Advanced Forms" },
  "Tables": { tags: ["<table", "<thead", "<tbody", "<tfoot", "<tr", "<th", "<td", "<caption", "<colgroup", "<col"], name: "Tables" },
  "Graphics & Rendering": { tags: ["<canvas", "<svg"], name: "Graphics & Rendering" },
  "Templates & Progressive Enhancement": { tags: ["<template", "<noscript"], name: "Templates & Progressive Enhancement" },
  "Accessibility & Internationalization": { tags: ["<abbr", "<bdi", "<bdo", "<ruby", "<rt", "<rp"], name: "Accessibility & Internationalization" },
  "Document Metadata & Contact": { tags: ["<address"], name: "Document Metadata & Contact" },
  "Developer & Technical Text": { tags: ["<kbd", "<samp", "<var"], name: "Developer & Technical Text" },
  "Document Editing & Revisions": { tags: ["<del", "<ins"], name: "Document Editing & Revisions" },
  "Definitions & Terminology": { tags: ["<dfn"], name: "Definitions & Terminology" },
  "Typography": { tags: ["<sub", "<sup", "<wbr"], name: "Typography" }
};
