export const componentMap: Record<string, string[]> = {
  "accessibility": [
    "Skip Link",
    "Focus Trap",
    "Visually Hidden",
    "ARIA Live Region",
    "Keyboard Input"
  ],
  "actions": [
    "Button",
    "Icon Button",
    "Toggle Button",
    "Button Group",
    "Split Button",
    "FAB",
    "Toggle Switch",
    "Checkbox",
    "Checkbox Group",
    "Radio Button",
    "Radio Group",
    "Slider",
    "Range Slider",
    "Chip",
    "Badge",
    "Icon",
    "Link",
    "Speed Dial",
    "Knob"
  ],
  "data": [
    "Table",
    "Data Grid",
    "List",
    "Tree",
    "Accordion",
    "Description List",
    "Avatar",
    "Avatar Group",
    "Calendar",
    "Timeline",
    "Chart",
    "Metric Card",
    "Carousel",
    "Compare",
    "Data View",
    "Gallery",
    "Image",
    "Organization Chart",
    "Pagination",
    "Virtual Scroll"
  ],
  "feedback": [
    "Alert",
    "Toast",
    "Notification",
    "Progress Bar",
    "Spinner",
    "Skeleton",
    "Empty State",
    "Status Indicator",
    "Message"
  ],
  "form": [
    "Form",
    "Form Field",
    "Fieldset",
    "Label",
    "Input",
    "Textarea",
    "Select",
    "Multi Select",
    "Date Picker",
    "Color Picker",
    "File Upload",
    "OTP Input",
    "Rating",
    "Signature Pad",
    "Autocomplete",
    "Time Picker",
    "DateTime Picker",
    "Icon Field",
    "Key Filter",
    "Listbox"
  ],
  "infrastructure": [
    "Router",
    "App Shell",
    "Provider",
    "Portal",
    "ErrorBoundary",
    "Core",
    "Localization (i18n)",
    "Overlay Service",
    "Theme"
  ],
  "layout": [
    "Container",
    "Section",
    "Box",
    "Card",
    "Paper",
    "Panel",
    "Grid",
    "Grid List",
    "Flex",
    "Stack",
    "Divider",
    "Separator",
    "Spacer",
    "Header",
    "Footer",
    "Sidebar",
    "Toolbar",
    "Split Pane/Panel/Screen/View",
    "Resizable Panel",
    "Scroll Area",
    "Aspect Ratio",
    "Splitter"
  ],
  "media": [
    "Thumbnail",
    "Lightbox",
    "Video Player",
    "Audio Player",
    "PDF Viewer"
  ],
  "navigation": [
    "Navbar",
    "Navigation Rail",
    "Bottom Navigation",
    "Menu",
    "Dropdown Menu",
    "Mega Menu",
    "Context Menu",
    "Breadcrumb",
    "Tabs",
    "Stepper",
    "Command Palette",
    "Sort Header",
    "Dock",
    "Drawer",
    "Filter Drawer",
    "Sidenav"
  ],
  "overlay": [
    "Dialog",
    "Tooltip",
    "Popover",
    "Overlay",
    "Bottom Sheet",
    "Confirm Dialog",
    "Confirm Popup",
    "Hover Card"
  ],
  "specialized": [
    "Login Form",
    "SSO Buttons",
    "Product Card",
    "Shopping Cart",
    "Checkout Form",
    "Chat Bubble",
    "Message Composer",
    "Stat Widget",
    "Activity Feed",
    "Prompt Input",
    "AI Response Block"
  ],
  "typography": [
    "Heading (h1-h6)",
    "Paragraph (p)",
    "Blockquote",
    "Code Block",
    "Mark / Highlight",
    "Caption",
    "Text"
  ],
  "utility": [
    "Copy To Clipboard",
    "Bind",
    "Class Names",
    "Filter Service",
    "Fluid",
    "Scroll Top"
  ],
  "visual": [
    "Shadow / Elevation",
    "Gradient",
    "Glassmorphism",
    "Mask",
    "Animation",
    "Animate On Scroll",
    "Auto Focus",
    "Block UI",
    "Ripple",
    "Style Class"
  ]
};